java_library(
    name = "application",
    srcs = [
        "CreateStudent.java",
        "StudentRepositoryStub.java"
    ],
    javacopts = ["-source", "17", "-target", "17"],
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/registry/domain/student:domain",
    ],
)

java_test(
    name = "CreateStudentTest",
    srcs = [
        "CreateStudentTest.java"
    ],
    javacopts = ["-source", "17", "-target", "17"],
    test_class = "pkg.registry.application.student.CreateStudentTest",
    deps = [
        ":application",
        "//pkg/registry/domain/student:domain",
        "//jvm-deps:junit",
    ],
)
